### PR TITLE
Provide COPYING.DJ

### PR DESCRIPTION
**Pull request by skitt**
stubify.c refers to this, ensure it's available.

### CODE REVIEW

**Comment by stsp** [comment]
Do you think its the right thing to do?
copying.dj refers to certain files and
libraries, none of which are relevant
here...
Also the file is 99% rewritten.
I guess it would be better if I strip the
references to COPYING.DJ instead?
Leaving only `Copyright (C) 2003 DJ Delorie`
as a reference to a previous author.

**Comment by stsp** [comment]
I just added a small clarification
that `COPYING.DJ` doesn't apply.

**Comment by skitt** [comment]
The second clause in `COPYING.DJ` applies to `stubify.c`:

> Any existing copyright or authorship information in any given source file must remain intact.  If you modify a source file, a notice to that effect must be added to the authorship information in the source file.

That’s common courtesy, but it is an additional requirement on top of the GPL.

IANAL, so I’m not sure whether rewriting the file means the requirement no longer applies; but I’m guessing it was rewritten as a succession of modifications to the original, rather than a new implementation from specifications, which would suggest that the additional requirement remains.

**Comment by skitt** [comment]
It probably doesn’t matter anyway :wink:

**Comment by stsp** [comment]
> Any existing copyright or authorship information in any given source file must remain intact. If you modify
> a source file, a notice to that effect must be added to the authorship information in the source file.

Yes, which is why I ended up not
stripping old copyrights, as initially
intended. :) They are still provided
as-is, and in fact, COPYING.DJ actually
applies only to them, by the quote
you pointed.

> rewritten as a succession of modifications to the original, rather than a new implementation from specifications,
> which would suggest that the additional requirement remains.

Yes, both statements are true.
It would be fine to add COPYING.DJ
then, but somehow it must be noted
that it only applies to those old
copyrights that can't be stripped or
edited...

**Pull request closed without merging**
